### ISSUE TITLE
Tab. Scrollbar

### ISSUE THREAD

**Issue by uzznick** [wvxwxvw/LibPortablePlus_Profiles#1]
Здравствуйте **wvxwxvw**! Большое спасибо за ваше творчество!
_Просьба по возможности ответить._
1. Не нашёл описания как отключить превю/эскизы страницы при наведении мыши в панели вкладок. В некоторых случаях рябит в глазах в темноте при светлом стиле страницы.
2. Как правильно подключить скроллы от [Quantum-Nox-Firefox-Dark-Full-Theme](https://github.com/Izheil/Quantum-Nox-Firefox-Dark-Full-Theme/tree/master/Full%20dark%20theme/Alternative%20scrollbars%20%26%20tooltips/Alternative%20scrollbars)?
В скриптах я 0, даже -1. Методом тыка включил так:
core\config.js добавил:
 ```
try {
 
 let Cu = Components.utils;
 Cu.import('resource://gre/modules/osfile.jsm');
 Cu.import(OS.Path.toFileURI(OS.Constants.Path.profileDir)+ '/chrome/utils/boot.jsm');
 
} catch(ex) {};
```
  profile\chrome добывил:
  scrollbars-minimal.as.css и [JS Loader](https://github.com/Izheil/Quantum-Nox-Firefox-Dark-Full-Theme/tree/master/Multirow%20and%20other%20functions/JS%20Loader/utils)

  profile\chrome\user_chrome_files\custom_scripts\CustomStylesScripts.jsm закомментировал:
  scrollbars.css
Работает, но не покидает чувство неграмотности метода.

**Comment by wvxwxvw** [comment]
@uzznick 
В нативной панели вкладок?
Закомментировать в CustomStylesScripts.jsm 
`            { path: "custom_js_win/dav_Tab_Title_URL.uc.js", ucfobj: false, },`
А для панели вкладок TST - есть кнопка отключения предпросмотра "TabPreview for TST"
  
Для стиля лоадер не нужен, UCF  сам по себе лоадер. Сделайте бэкап профиля, удалите лоадер, положите scrollbars-minimal.as.css рядом с scrollbars.css и подключите scrollbars-minimal.as.css в CustomStylesScripts.jsm, так;
было
```
        { path: "scrollbars.css", type: "AGENT_SHEET", sheet() { registerSheet(this); }, }, // <-- Скроллбар
```
стало
```
        // { path: "scrollbars.css", type: "AGENT_SHEET", sheet() { registerSheet(this); }, }, // <-- Скроллбар  
        { path: "scrollbars-minimal.as.css", type: "AGENT_SHEET", sheet() { registerSheet(this); }, }, // <-- Скроллбар
```
